load_first:
  - lib/jasmine/lib/jasmine-0.10.3.js
  - app/lib/pockets.js
  - app/lib/pockets-dom.js
  - app/lib/pockets-ui.js
  - app/assistants/test-assistant.js
  - app/models/test-list-widget.js
  - app/models/test-progress-widget.js
  - app/models/error-list-widget.js
  - app/lib/dom-pretty-printer.js
  - app/lib/pockets-fake-depot.js
  - app/lib/pockets-mock-ajax.js
  - app/lib/matchers.js
  - app/lib/pockets-test.js
  - app/lib/pockets-test-ui.js
  - app/lib/ajax-reporter.js
  - app/lib/json-pretty-printer.js
